// Code generated by entc, DO NOT EDIT.

package book

const (
	// Label holds the string label denoting the book type in the database.
	Label = "book"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBOOKNAME holds the string denoting the book_name field in the database.
	FieldBOOKNAME = "book_name"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"

	// EdgeBooklist holds the string denoting the booklist edge name in mutations.
	EdgeBooklist = "Booklist"

	// Table holds the table name of the book in the database.
	Table = "books"
	// BooklistTable is the table the holds the Booklist relation/edge.
	BooklistTable = "book_borrows"
	// BooklistInverseTable is the table name for the BookBorrow entity.
	// It exists in this package in order to avoid circular dependency with the "bookborrow" package.
	BooklistInverseTable = "book_borrows"
	// BooklistColumn is the table column denoting the Booklist relation/edge.
	BooklistColumn = "BOOK_ID"
)

// Columns holds all SQL columns for book fields.
var Columns = []string{
	FieldID,
	FieldBOOKNAME,
	FieldAuthor,
	FieldStatus,
}

var (
	// BOOKNAMEValidator is a validator for the "BOOK_NAME" field. It is called by the builders before save.
	BOOKNAMEValidator func(string) error
)
