// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUSEREMAIL holds the string denoting the user_email field in the database.
	FieldUSEREMAIL = "user_email"
	// FieldUSERNAME holds the string denoting the user_name field in the database.
	FieldUSERNAME = "user_name"

	// EdgeBooklist holds the string denoting the booklist edge name in mutations.
	EdgeBooklist = "Booklist"
	// EdgeRolePlay holds the string denoting the roleplay edge name in mutations.
	EdgeRolePlay = "RolePlay"

	// Table holds the table name of the user in the database.
	Table = "users"
	// BooklistTable is the table the holds the Booklist relation/edge.
	BooklistTable = "book_borrows"
	// BooklistInverseTable is the table name for the BookBorrow entity.
	// It exists in this package in order to avoid circular dependency with the "bookborrow" package.
	BooklistInverseTable = "book_borrows"
	// BooklistColumn is the table column denoting the Booklist relation/edge.
	BooklistColumn = "user_booklist"
	// RolePlayTable is the table the holds the RolePlay relation/edge.
	RolePlayTable = "users"
	// RolePlayInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RolePlayInverseTable = "roles"
	// RolePlayColumn is the table column denoting the RolePlay relation/edge.
	RolePlayColumn = "ROLE_ID"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUSEREMAIL,
	FieldUSERNAME,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the User type.
var ForeignKeys = []string{
	"ROLE_ID",
}

var (
	// USEREMAILValidator is a validator for the "USER_EMAIL" field. It is called by the builders before save.
	USEREMAILValidator func(string) error
	// USERNAMEValidator is a validator for the "USER_NAME" field. It is called by the builders before save.
	USERNAMEValidator func(string) error
)
