// Code generated by entc, DO NOT EDIT.

package purpose

const (
	// Label holds the string label denoting the purpose type in the database.
	Label = "purpose"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPURPOSENAME holds the string denoting the purpose_name field in the database.
	FieldPURPOSENAME = "purpose_name"

	// EdgeFor holds the string denoting the for edge name in mutations.
	EdgeFor = "for"

	// Table holds the table name of the purpose in the database.
	Table = "purposes"
	// ForTable is the table the holds the for relation/edge.
	ForTable = "book_borrows"
	// ForInverseTable is the table name for the BookBorrow entity.
	// It exists in this package in order to avoid circular dependency with the "bookborrow" package.
	ForInverseTable = "book_borrows"
	// ForColumn is the table column denoting the for relation/edge.
	ForColumn = "PURPOSE_ID"
)

// Columns holds all SQL columns for purpose fields.
var Columns = []string{
	FieldID,
	FieldPURPOSENAME,
}

var (
	// PURPOSENAMEValidator is a validator for the "PURPOSE_NAME" field. It is called by the builders before save.
	PURPOSENAMEValidator func(string) error
)
