// Code generated by entc, DO NOT EDIT.

package purpose

const (
	// Label holds the string label denoting the purpose type in the database.
	Label = "purpose"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPURPOSEID holds the string denoting the purpose_id field in the database.
	FieldPURPOSEID = "purpose_id"
	// FieldPURPOSENAME holds the string denoting the purpose_name field in the database.
	FieldPURPOSENAME = "purpose_name"

	// EdgeBooklist holds the string denoting the booklist edge name in mutations.
	EdgeBooklist = "Booklist"

	// Table holds the table name of the purpose in the database.
	Table = "purposes"
	// BooklistTable is the table the holds the Booklist relation/edge.
	BooklistTable = "book_borrows"
	// BooklistInverseTable is the table name for the BookBorrow entity.
	// It exists in this package in order to avoid circular dependency with the "bookborrow" package.
	BooklistInverseTable = "book_borrows"
	// BooklistColumn is the table column denoting the Booklist relation/edge.
	BooklistColumn = "purpose_booklist"
)

// Columns holds all SQL columns for purpose fields.
var Columns = []string{
	FieldID,
	FieldPURPOSEID,
	FieldPURPOSENAME,
}

var (
	// PURPOSEIDValidator is a validator for the "PURPOSE_ID" field. It is called by the builders before save.
	PURPOSEIDValidator func(int) error
	// PURPOSENAMEValidator is a validator for the "PURPOSE_NAME" field. It is called by the builders before save.
	PURPOSENAMEValidator func(string) error
)
