// Code generated by entc, DO NOT EDIT.

package bookborrow

const (
	// Label holds the string label denoting the bookborrow type in the database.
	Label = "book_borrow"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldADDEDTIME holds the string denoting the added_time field in the database.
	FieldADDEDTIME = "added_time"

	// EdgeUSER holds the string denoting the user edge name in mutations.
	EdgeUSER = "USER"
	// EdgeBOOK holds the string denoting the book edge name in mutations.
	EdgeBOOK = "BOOK"
	// EdgePURPOSE holds the string denoting the purpose edge name in mutations.
	EdgePURPOSE = "PURPOSE"

	// Table holds the table name of the bookborrow in the database.
	Table = "book_borrows"
	// USERTable is the table the holds the USER relation/edge.
	USERTable = "book_borrows"
	// USERInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	USERInverseTable = "users"
	// USERColumn is the table column denoting the USER relation/edge.
	USERColumn = "User_ID"
	// BOOKTable is the table the holds the BOOK relation/edge.
	BOOKTable = "book_borrows"
	// BOOKInverseTable is the table name for the Book entity.
	// It exists in this package in order to avoid circular dependency with the "book" package.
	BOOKInverseTable = "books"
	// BOOKColumn is the table column denoting the BOOK relation/edge.
	BOOKColumn = "BOOK_ID"
	// PURPOSETable is the table the holds the PURPOSE relation/edge.
	PURPOSETable = "book_borrows"
	// PURPOSEInverseTable is the table name for the Purpose entity.
	// It exists in this package in order to avoid circular dependency with the "purpose" package.
	PURPOSEInverseTable = "purposes"
	// PURPOSEColumn is the table column denoting the PURPOSE relation/edge.
	PURPOSEColumn = "PURPOSE_ID"
)

// Columns holds all SQL columns for bookborrow fields.
var Columns = []string{
	FieldID,
	FieldADDEDTIME,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the BookBorrow type.
var ForeignKeys = []string{
	"BOOK_ID",
	"PURPOSE_ID",
	"User_ID",
}
