// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/B6102647/app/ent/book"
	"github.com/B6102647/app/ent/bookborrow"
	"github.com/B6102647/app/ent/predicate"
	"github.com/B6102647/app/ent/status"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks      []Hook
	mutation   *BookMutation
	predicates []predicate.Book
}

// Where adds a new predicate for the builder.
func (bu *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	bu.predicates = append(bu.predicates, ps...)
	return bu
}

// SetBOOKNAME sets the BOOK_NAME field.
func (bu *BookUpdate) SetBOOKNAME(s string) *BookUpdate {
	bu.mutation.SetBOOKNAME(s)
	return bu
}

// SetUSERNAME sets the USER_NAME field.
func (bu *BookUpdate) SetUSERNAME(s string) *BookUpdate {
	bu.mutation.SetUSERNAME(s)
	return bu
}

// SetCATEGORY sets the CATEGORY field.
func (bu *BookUpdate) SetCATEGORY(s string) *BookUpdate {
	bu.mutation.SetCATEGORY(s)
	return bu
}

// SetAuthor sets the Author field.
func (bu *BookUpdate) SetAuthor(s string) *BookUpdate {
	bu.mutation.SetAuthor(s)
	return bu
}

// AddBooklistIDs adds the Booklist edge to BookBorrow by ids.
func (bu *BookUpdate) AddBooklistIDs(ids ...int) *BookUpdate {
	bu.mutation.AddBooklistIDs(ids...)
	return bu
}

// AddBooklist adds the Booklist edges to BookBorrow.
func (bu *BookUpdate) AddBooklist(b ...*BookBorrow) *BookUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return bu.AddBooklistIDs(ids...)
}

// SetStatusID sets the Status edge to Status by id.
func (bu *BookUpdate) SetStatusID(id int) *BookUpdate {
	bu.mutation.SetStatusID(id)
	return bu
}

// SetNillableStatusID sets the Status edge to Status by id if the given value is not nil.
func (bu *BookUpdate) SetNillableStatusID(id *int) *BookUpdate {
	if id != nil {
		bu = bu.SetStatusID(*id)
	}
	return bu
}

// SetStatus sets the Status edge to Status.
func (bu *BookUpdate) SetStatus(s *Status) *BookUpdate {
	return bu.SetStatusID(s.ID)
}

// Mutation returns the BookMutation object of the builder.
func (bu *BookUpdate) Mutation() *BookMutation {
	return bu.mutation
}

// RemoveBooklistIDs removes the Booklist edge to BookBorrow by ids.
func (bu *BookUpdate) RemoveBooklistIDs(ids ...int) *BookUpdate {
	bu.mutation.RemoveBooklistIDs(ids...)
	return bu
}

// RemoveBooklist removes Booklist edges to BookBorrow.
func (bu *BookUpdate) RemoveBooklist(b ...*BookBorrow) *BookUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return bu.RemoveBooklistIDs(ids...)
}

// ClearStatus clears the Status edge to Status.
func (bu *BookUpdate) ClearStatus() *BookUpdate {
	bu.mutation.ClearStatus()
	return bu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (bu *BookUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := bu.mutation.BOOKNAME(); ok {
		if err := book.BOOKNAMEValidator(v); err != nil {
			return 0, &ValidationError{Name: "BOOK_NAME", err: fmt.Errorf("ent: validator failed for field \"BOOK_NAME\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(bu.hooks) == 0 {
		affected, err = bu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BookMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bu.mutation = mutation
			affected, err = bu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bu.hooks) - 1; i >= 0; i-- {
			mut = bu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BookUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BookUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BookUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   book.Table,
			Columns: book.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: book.FieldID,
			},
		},
	}
	if ps := bu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.BOOKNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: book.FieldBOOKNAME,
		})
	}
	if value, ok := bu.mutation.USERNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: book.FieldUSERNAME,
		})
	}
	if value, ok := bu.mutation.CATEGORY(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: book.FieldCATEGORY,
		})
	}
	if value, ok := bu.mutation.Author(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: book.FieldAuthor,
		})
	}
	if nodes := bu.mutation.RemovedBooklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BooklistTable,
			Columns: []string{book.BooklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookborrow.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.BooklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BooklistTable,
			Columns: []string{book.BooklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookborrow.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if bu.mutation.StatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.StatusTable,
			Columns: []string{book.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: status.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.StatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.StatusTable,
			Columns: []string{book.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: status.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// SetBOOKNAME sets the BOOK_NAME field.
func (buo *BookUpdateOne) SetBOOKNAME(s string) *BookUpdateOne {
	buo.mutation.SetBOOKNAME(s)
	return buo
}

// SetUSERNAME sets the USER_NAME field.
func (buo *BookUpdateOne) SetUSERNAME(s string) *BookUpdateOne {
	buo.mutation.SetUSERNAME(s)
	return buo
}

// SetCATEGORY sets the CATEGORY field.
func (buo *BookUpdateOne) SetCATEGORY(s string) *BookUpdateOne {
	buo.mutation.SetCATEGORY(s)
	return buo
}

// SetAuthor sets the Author field.
func (buo *BookUpdateOne) SetAuthor(s string) *BookUpdateOne {
	buo.mutation.SetAuthor(s)
	return buo
}

// AddBooklistIDs adds the Booklist edge to BookBorrow by ids.
func (buo *BookUpdateOne) AddBooklistIDs(ids ...int) *BookUpdateOne {
	buo.mutation.AddBooklistIDs(ids...)
	return buo
}

// AddBooklist adds the Booklist edges to BookBorrow.
func (buo *BookUpdateOne) AddBooklist(b ...*BookBorrow) *BookUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return buo.AddBooklistIDs(ids...)
}

// SetStatusID sets the Status edge to Status by id.
func (buo *BookUpdateOne) SetStatusID(id int) *BookUpdateOne {
	buo.mutation.SetStatusID(id)
	return buo
}

// SetNillableStatusID sets the Status edge to Status by id if the given value is not nil.
func (buo *BookUpdateOne) SetNillableStatusID(id *int) *BookUpdateOne {
	if id != nil {
		buo = buo.SetStatusID(*id)
	}
	return buo
}

// SetStatus sets the Status edge to Status.
func (buo *BookUpdateOne) SetStatus(s *Status) *BookUpdateOne {
	return buo.SetStatusID(s.ID)
}

// Mutation returns the BookMutation object of the builder.
func (buo *BookUpdateOne) Mutation() *BookMutation {
	return buo.mutation
}

// RemoveBooklistIDs removes the Booklist edge to BookBorrow by ids.
func (buo *BookUpdateOne) RemoveBooklistIDs(ids ...int) *BookUpdateOne {
	buo.mutation.RemoveBooklistIDs(ids...)
	return buo
}

// RemoveBooklist removes Booklist edges to BookBorrow.
func (buo *BookUpdateOne) RemoveBooklist(b ...*BookBorrow) *BookUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return buo.RemoveBooklistIDs(ids...)
}

// ClearStatus clears the Status edge to Status.
func (buo *BookUpdateOne) ClearStatus() *BookUpdateOne {
	buo.mutation.ClearStatus()
	return buo
}

// Save executes the query and returns the updated entity.
func (buo *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	if v, ok := buo.mutation.BOOKNAME(); ok {
		if err := book.BOOKNAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "BOOK_NAME", err: fmt.Errorf("ent: validator failed for field \"BOOK_NAME\": %w", err)}
		}
	}

	var (
		err  error
		node *Book
	)
	if len(buo.hooks) == 0 {
		node, err = buo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BookMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			buo.mutation = mutation
			node, err = buo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(buo.hooks) - 1; i >= 0; i-- {
			mut = buo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, buo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BookUpdateOne) SaveX(ctx context.Context) *Book {
	b, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return b
}

// Exec executes the query on the entity.
func (buo *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BookUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BookUpdateOne) sqlSave(ctx context.Context) (b *Book, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   book.Table,
			Columns: book.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: book.FieldID,
			},
		},
	}
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Book.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := buo.mutation.BOOKNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: book.FieldBOOKNAME,
		})
	}
	if value, ok := buo.mutation.USERNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: book.FieldUSERNAME,
		})
	}
	if value, ok := buo.mutation.CATEGORY(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: book.FieldCATEGORY,
		})
	}
	if value, ok := buo.mutation.Author(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: book.FieldAuthor,
		})
	}
	if nodes := buo.mutation.RemovedBooklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BooklistTable,
			Columns: []string{book.BooklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookborrow.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.BooklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BooklistTable,
			Columns: []string{book.BooklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookborrow.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if buo.mutation.StatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.StatusTable,
			Columns: []string{book.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: status.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.StatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.StatusTable,
			Columns: []string{book.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: status.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	b = &Book{config: buo.config}
	_spec.Assign = b.assignValues
	_spec.ScanValues = b.scanValues()
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return b, nil
}
