// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/B6102647/app/ent/bookborrow"
	"github.com/B6102647/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// BookBorrowDelete is the builder for deleting a BookBorrow entity.
type BookBorrowDelete struct {
	config
	hooks      []Hook
	mutation   *BookBorrowMutation
	predicates []predicate.BookBorrow
}

// Where adds a new predicate to the delete builder.
func (bbd *BookBorrowDelete) Where(ps ...predicate.BookBorrow) *BookBorrowDelete {
	bbd.predicates = append(bbd.predicates, ps...)
	return bbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bbd *BookBorrowDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(bbd.hooks) == 0 {
		affected, err = bbd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BookBorrowMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bbd.mutation = mutation
			affected, err = bbd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bbd.hooks) - 1; i >= 0; i-- {
			mut = bbd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bbd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (bbd *BookBorrowDelete) ExecX(ctx context.Context) int {
	n, err := bbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bbd *BookBorrowDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: bookborrow.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bookborrow.FieldID,
			},
		},
	}
	if ps := bbd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, bbd.driver, _spec)
}

// BookBorrowDeleteOne is the builder for deleting a single BookBorrow entity.
type BookBorrowDeleteOne struct {
	bbd *BookBorrowDelete
}

// Exec executes the deletion query.
func (bbdo *BookBorrowDeleteOne) Exec(ctx context.Context) error {
	n, err := bbdo.bbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bookborrow.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bbdo *BookBorrowDeleteOne) ExecX(ctx context.Context) {
	bbdo.bbd.ExecX(ctx)
}
