// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/B6102647/app/ent/bookborrow"
	"github.com/B6102647/app/ent/purpose"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// PurposeCreate is the builder for creating a Purpose entity.
type PurposeCreate struct {
	config
	mutation *PurposeMutation
	hooks    []Hook
}

// SetPURPOSENAME sets the PURPOSE_NAME field.
func (pc *PurposeCreate) SetPURPOSENAME(s string) *PurposeCreate {
	pc.mutation.SetPURPOSENAME(s)
	return pc
}

// AddBooklistIDs adds the Booklist edge to BookBorrow by ids.
func (pc *PurposeCreate) AddBooklistIDs(ids ...int) *PurposeCreate {
	pc.mutation.AddBooklistIDs(ids...)
	return pc
}

// AddBooklist adds the Booklist edges to BookBorrow.
func (pc *PurposeCreate) AddBooklist(b ...*BookBorrow) *PurposeCreate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return pc.AddBooklistIDs(ids...)
}

// Mutation returns the PurposeMutation object of the builder.
func (pc *PurposeCreate) Mutation() *PurposeMutation {
	return pc.mutation
}

// Save creates the Purpose in the database.
func (pc *PurposeCreate) Save(ctx context.Context) (*Purpose, error) {
	if _, ok := pc.mutation.PURPOSENAME(); !ok {
		return nil, &ValidationError{Name: "PURPOSE_NAME", err: errors.New("ent: missing required field \"PURPOSE_NAME\"")}
	}
	if v, ok := pc.mutation.PURPOSENAME(); ok {
		if err := purpose.PURPOSENAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "PURPOSE_NAME", err: fmt.Errorf("ent: validator failed for field \"PURPOSE_NAME\": %w", err)}
		}
	}
	var (
		err  error
		node *Purpose
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PurposeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PurposeCreate) SaveX(ctx context.Context) *Purpose {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PurposeCreate) sqlSave(ctx context.Context) (*Purpose, error) {
	pu, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pu.ID = int(id)
	return pu, nil
}

func (pc *PurposeCreate) createSpec() (*Purpose, *sqlgraph.CreateSpec) {
	var (
		pu    = &Purpose{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: purpose.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: purpose.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.PURPOSENAME(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: purpose.FieldPURPOSENAME,
		})
		pu.PURPOSENAME = value
	}
	if nodes := pc.mutation.BooklistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   purpose.BooklistTable,
			Columns: []string{purpose.BooklistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookborrow.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pu, _spec
}
