// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/B6102647/app/ent/book"
	"github.com/B6102647/app/ent/purpose"
	"github.com/B6102647/app/ent/role"
	"github.com/B6102647/app/ent/schema"
	"github.com/B6102647/app/ent/user"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescBOOKNAME is the schema descriptor for BOOK_NAME field.
	bookDescBOOKNAME := bookFields[0].Descriptor()
	// book.BOOKNAMEValidator is a validator for the "BOOK_NAME" field. It is called by the builders before save.
	book.BOOKNAMEValidator = bookDescBOOKNAME.Validators[0].(func(string) error)
	purposeFields := schema.Purpose{}.Fields()
	_ = purposeFields
	// purposeDescPURPOSENAME is the schema descriptor for PURPOSE_NAME field.
	purposeDescPURPOSENAME := purposeFields[0].Descriptor()
	// purpose.PURPOSENAMEValidator is a validator for the "PURPOSE_NAME" field. It is called by the builders before save.
	purpose.PURPOSENAMEValidator = purposeDescPURPOSENAME.Validators[0].(func(string) error)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescROLENAME is the schema descriptor for ROLE_NAME field.
	roleDescROLENAME := roleFields[0].Descriptor()
	// role.ROLENAMEValidator is a validator for the "ROLE_NAME" field. It is called by the builders before save.
	role.ROLENAMEValidator = roleDescROLENAME.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUSEREMAIL is the schema descriptor for USER_EMAIL field.
	userDescUSEREMAIL := userFields[0].Descriptor()
	// user.USEREMAILValidator is a validator for the "USER_EMAIL" field. It is called by the builders before save.
	user.USEREMAILValidator = userDescUSEREMAIL.Validators[0].(func(string) error)
	// userDescUSERNAME is the schema descriptor for USER_NAME field.
	userDescUSERNAME := userFields[1].Descriptor()
	// user.USERNAMEValidator is a validator for the "USER_NAME" field. It is called by the builders before save.
	user.USERNAMEValidator = userDescUSERNAME.Validators[0].(func(string) error)
}
