// Code generated by entc, DO NOT EDIT.

package status

const (
	// Label holds the string label denoting the status type in the database.
	Label = "status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSTATUSNAME holds the string denoting the status_name field in the database.
	FieldSTATUSNAME = "status_name"

	// EdgeStatus holds the string denoting the status edge name in mutations.
	EdgeStatus = "status"

	// Table holds the table name of the status in the database.
	Table = "status"
	// StatusTable is the table the holds the status relation/edge.
	StatusTable = "books"
	// StatusInverseTable is the table name for the Book entity.
	// It exists in this package in order to avoid circular dependency with the "book" package.
	StatusInverseTable = "books"
	// StatusColumn is the table column denoting the status relation/edge.
	StatusColumn = "STATUS_ID"
)

// Columns holds all SQL columns for status fields.
var Columns = []string{
	FieldID,
	FieldSTATUSNAME,
}
