/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBookBorrowEdges,
    EntBookBorrowEdgesFromJSON,
    EntBookBorrowEdgesFromJSONTyped,
    EntBookBorrowEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBookBorrow
 */
export interface EntBookBorrow {
    /**
     * ADDEDTIME holds the value of the "ADDED_TIME" field.
     * @type {string}
     * @memberof EntBookBorrow
     */
    aDDEDTIME?: string;
    /**
     * 
     * @type {number}
     * @memberof EntBookBorrow
     */
    bookID?: number;
    /**
     * 
     * @type {EntBookBorrowEdges}
     * @memberof EntBookBorrow
     */
    edges?: EntBookBorrowEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntBookBorrow
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof EntBookBorrow
     */
    purposeID?: number;
    /**
     * 
     * @type {number}
     * @memberof EntBookBorrow
     */
    userID?: number;
}

export function EntBookBorrowFromJSON(json: any): EntBookBorrow {
    return EntBookBorrowFromJSONTyped(json, false);
}

export function EntBookBorrowFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBookBorrow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aDDEDTIME': !exists(json, 'ADDED_TIME') ? undefined : json['ADDED_TIME'],
        'bookID': !exists(json, 'book_ID') ? undefined : json['book_ID'],
        'edges': !exists(json, 'edges') ? undefined : EntBookBorrowEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'purposeID': !exists(json, 'purpose_ID') ? undefined : json['purpose_ID'],
        'userID': !exists(json, 'user_ID') ? undefined : json['user_ID'],
    };
}

export function EntBookBorrowToJSON(value?: EntBookBorrow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ADDED_TIME': value.aDDEDTIME,
        'book_ID': value.bookID,
        'edges': EntBookBorrowEdgesToJSON(value.edges),
        'id': value.id,
        'purpose_ID': value.purposeID,
        'user_ID': value.userID,
    };
}


